obj-m := sped_first.o w5500-spi.o

all: 
#	make -C /home/pradeep/Trainings/Rpi/Kernel/linux M=$(PWD) modules
	make -C /home/pradeep/Trainings/Bosch/device_drivers/Builds/OS/linux-6.12.54 M=$(PWD) modules
clean:
	make -C /home/pradeep/Trainings/Rpi/Kernel/linux M=$(PWD) clean
